apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  labels:
    ## This label is applied to DaemonSet
    app: nginx
    gpuexist: "true"
spec:
  selector:
    matchLabels:
      name: nginx
  template:
    metadata:
      labels:
        app: nginx
        gpuexist: "true"
        name: nginx
    spec:
      nodeSelector:  # kubectl label --list nodes node_name (or) kubectl get nodes --show-labels
        gpuexist: "true" # to assign a label to a node "kubectl label nodes <node-name> <key=value> / kubectl label nodes node01 gpuexist=true"
      containers:
        - name: nginx
          image: nginx:1.10.0
          